### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vibraphone** [Kitware/kw-doc#2]
There does not appear to be any documentation and the example is very minimal.

+ What is the relationship between `data/menu.yml`, `tpl/__en__`, and `tpl/__sidebar__`?
+ How are banners or other background elements created in the main `index.jade` file?
+ How would blog or other posts get added? I see `build-tmp/public/2016/04/28/kw-doc/index.html` and `build-tmp/public/news/2016/04/index.html` files are created, but not where content should go if we want it added.
+ Was the kw-doc theme taken from a hexo theme? If so, was that theme documented? Does its documentation answer any of the above?

**Comment by jourdain** [comment]
- menu is the horizontal top bar / sidebar is all the vertical ones. __en__ is the translation for everything.
- some come from the config
- need to add a menu pointing to news
- yes from their doc web site, but then tuned so it match our documentation goal. Everything is static on their end, I just made some part dynamic.

**Comment by jourdain** [comment]
I think the news template infrastructure will take care of that. So the menu.yml should just point to the root.

**Comment by jourdain** [comment]
But I'm rusty on that, since I probably worked on it 2-3 years ago...

**Comment by vibraphone** [comment]
It might be nice to adapt [SENSEI's documentation](https://gitlab.kitware.com/sensei/sensei/blob/master/doc/content/_posts/20180504-website.md), which addresses most of these issues, into something generic enough for kw-doc.

I still don't see anything in kw-doc or hexo that serves as an example of a banner/background image.
